### ISSUE TITLE
error when running the code 

### ISSUE THREAD

**Issue by zhutengjie** [SonSang/dmesh#1]
Thanks for your great work. I built the environment successfully following the instructions , however , I met this error when running the code :
Traceback (most recent call last):
  File "/data/cz/dmesh/exp/1_mesh_to_dmesh.py", line 16, in <module>
    from diffdt import DiffDT
  File "/data/cz/dmesh/diffdt/__init__.py", line 5, in <module>
    from diffdt.pd import PDVertexComputationLayer, PDStruct
  File "/data/cz/dmesh/diffdt/pd.py", line 8, in <module>
    from . import _C
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory

**Comment by SonSang** [comment]
Hi, can you please check if you correctly installed OneTBB, following the instruction?
It seems that OneTBB has not been installed.

**Comment by zhutengjie** [comment]
Thanks, I upgraded the version of torch to 2.2.1 and updated the version of Cmake, and now the problem is solved

**Comment by SonSang** [comment]
Great, thanks for your interest!

**Comment by astonishingwolf** [comment]
Awesome work!!
Unfortunately, I am still facing the same issues. I have installed everything according to the README description but I am finding myself stuck on this issue :
Traceback (most recent call last):
  File "/home/astonishingwolf/3d-graphics/dmesh/exp/2_pc_recon.py", line 10, in <module>
    from exp.recon import BaseRecon, DEVICE, DOMAIN
  File "/home/astonishingwolf/3d-graphics/dmesh/exp/recon.py", line 6, in <module>
    from diffdt.wp import WPoints
  File "/home/astonishingwolf/3d-graphics/dmesh/diffdt/__init__.py", line 5, in <module>
    from diffdt.pd import PDVertexComputationLayer, PDStruct
  File "/home/astonishingwolf/3d-graphics/dmesh/diffdt/pd.py", line 8, in <module>
    from . import _C
ImportError: libtbb.so.12: cannot open shared object file: No such file or directory
One TBB seems to be installed.  I have installed Pytorch version 2.2.1 and upgraded my CMake as well but the error still persists. Any clue why this problem might be occurring?

**Comment by SonSang** [comment]
Hi, can you check if OneTBB has been installed correctly? Can you find installed files in external/oneTBB/install ?

**Comment by astonishingwolf** [comment]
Hi,
Thanks for replying. Adding the path to the library as an environment variable solved it for me. 
`export LD_LIBRARY_PATH=$DMESH_PATH/external/oneTBB/install/lib:$LD_LIBRARY_PATH`
Thanks for your help

**Comment by SonSang** [comment]
Glad it worked, thanks!!
